volumes:
  certs:          # Certbot outputs SSL cerfiticates
  acme:           # Where certbot execs the ACME challenge

services:

  # -----------------------------------------
  # webserver
  # -----------------------------------------

  nginx:
    build:
      context: ./nginx
      additional_contexts:
        - www=docker-image://klcom-w3
    restart: always
    volumes:
      - certs:/etc/nginx/ssl:ro
      - acme:/var/www/acme:ro
    ports:
      - '80:80'
      - '443:443'

  # -----------------------------------------
  # Let's Encrypt
  # -----------------------------------------

  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    restart: no                # run & exit
    volumes:
      - certs:/etc/letsencrypt:rw
      - acme:/var/www/html:rw
    command: >
      certonly
      --cert-name keyli3e.com
      -d keyli3e.com,www.keyli3e.com
      --webroot -w /var/www/html
      -m "$CERT_EMAIL"
      --non-interactive
      --agree-tos
    profiles:
      - certs
