volumes:
  w3:             # Public assets to be served by Nginx
  certs:          # Certbot outputs SSL cerfiticates
  acme:           # Where certbot execs the ACME challenge
  w3log:          # Nginx logs

services:

  # ----------------------------------------
  # nginx - reverse proxy
  # ----------------------------------------

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - certs:/etc/nginx/ssl:ro
      - w3:/var/www/html:ro
      - acme:/var/www/acme:ro
      - w3log:/var/log/nginx:rw
    ports:
      - '80:80'
      - '443:443'
    profiles:
      - web
      - certs

  # ----------------------------------------
  # Let's Encrypt
  # ----------------------------------------

  certbot:
    image: certbot/cerbot
    depends_on:
      - nginx
    restart: no                # run & exit
    volumes:
      - certs:/etc/letsencrypt:rw
      - acme:/var/www/html:rw
    command: >
      certonly
      --webroot -w /var/www/html
      -d "keyli3e.com"
      -d "www.keyli3e.com"
      -m "$CONTACT_EMAIL"
      --non-interactive
      --agree-tos
    profiles:
      - certs

  # ----------------------------------------
  # Git-sync
  # ----------------------------------------

  # w3-sync:
  #   image: registry.k8s.io/git-sync/git-sync:v4.3.0
  #   restart: always
  #   user: 1000:1000
  #   volumes:
  #     - ./git:/cfg:ro
  #     - w3-src:/tmp/git
  #   command: >
  #     --repo=git@github.com:tnlx/keyli3e.com.git
  #     --root=/tmp/git/root
  #     --period=5m
  #     --ssh-key-file=/cfg/id_ed25519

  # ----------------------------------------
  # w3-build
  # ----------------------------------------

  w3-build:
    build:
      context: git@github.com:tnlx/keyli3e.com.git#main
      ssh:
        - default              # mount the default SSH agent
      no_cache: true
      args:
        BUILDKIT_CONTEXT_KEEP_GIT_DIR: 1
    restart: no                # run & exit
    volumes:
        - w3:/html:rw
    command: >
      --baseURL https://keyli3e.com
      --destination /html
    profiles:
      - web
