volumes:
  w3:             # Public assets to be served by Nginx
  certs:          # Certbot outputs SSL cerfiticates
  acme:           # Where certbot execs the ACME challenge

services:

  # -----------------------------------------
  # webserver
  # -----------------------------------------

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - certs:/etc/nginx/ssl:ro
      - w3:/usr/share/nginx/html/:ro
      - acme:/var/www/acme:ro
    ports:
      - '80:80'
      - '443:443'
    profiles:
      - web
      - certs

  # -----------------------------------------
  # Let's Encrypt
  # -----------------------------------------

  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    restart: no                # run & exit
    volumes:
      - certs:/etc/letsencrypt:rw
      - acme:/var/www/html:rw
    command: >
      certonly
      -d "keyli3e.com"
      -d "www.keyli3e.com"
      --webroot -w /var/www/html
      -m "$CERT_EMAIL"
      --non-interactive
      --agree-tos
    profiles:
      - certs

  # -----------------------------------------
  # w3-build
  #   SSH_KEY_KLCOM: path to the ssh key with
  #                  access to the repository
  # -----------------------------------------

  w3-build:
    build:
      context: git@github.com:tnlx/keyli3e.com.git#main
      ssh:
        - default=$SSH_KEY_KLCOM
      args:
        BUILDKIT_CONTEXT_KEEP_GIT_DIR: 1
    restart: no                # run & exit
    volumes:
      - w3:/html:rw
    profiles:
      - web
      - build
